### ISSUE TITLE
Dates for MOOC, and typos

### ISSUE THREAD

**Issue by Beliavsky** [gjbex/DPD-online-book#8]
At https://www.futurelearn.com/courses/defensive-programming-and-debugging it says the dates of instructor participation are 
`31 Mar 2022 - 31 Mar 2022`, which is only one day. I assume that's a typo.

At https://gjbex.github.io/DPD-online-book/ the word "conntribute" should be "contribute".

I [tweeted about your MOOC](https://twitter.com/fortrantip/status/1509557710810980358). Good luck.

**Comment by gjbex** [comment]
@Beliavsky Thanks for the feedback and for tweeting about Defensive Programming and Debugging.

I had set a number of participation dates when the fifth run started but forgot to add new ones, which I did today.  Typically, I have a quick look every day anyway (except for the next two weeks).

The typo is also fixed.
